### ISSUE TITLE
undefined reference to `sprintf'

### ISSUE THREAD

**Issue by duxiaoshi** [vortex314/stm32_programmer#1]
**Error Infos**
pan@ubuntu:~/eggtoy_workspace/stm32_programmer$ make
Linking ./build/main.bin
  Versions: cef5ed6-dirty, 2.3.0-69-g4897e00
build/obj/main.cpp.o: In function `waitConfig()':
/home/pan/eggtoy_workspace/stm32_programmer/main.cpp:50: undefined reference to`sprintf'
build/obj/main.cpp.o: In function `set<String&>':
/home/pan/eggtoy_workspace/stm32_programmer/main.cpp:50: undefined reference to`sprintf'
build/obj/core.ar(core_esp8266_main.cpp.o): In function `optimistic_yield':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp:56: undefined reference to`printf'
build/obj/core.ar(core_esp8266_main.cpp.o): In function `do_global_ctors':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp:56: undefined reference to`printf'
build/obj/core.ar(umm_malloc.c.o): In function `umm_info':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:991: undefined reference to`printf'
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1024: undefined reference to `printf'
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1043: undefined reference to`printf'
build/obj/core.ar(umm_malloc.c.o):/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1072: more undefined references to `printf' follow
build/obj/core.ar(Print.cpp.o): In function`Print::printf(char const_, ...)':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/Print.cpp:99: undefined reference to `vsnprintf'
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/Print.cpp:99: undefined reference to`vsnprintf'
build/obj/Log.cpp.o: In function `LogManager::~LogManager()':
/home/pan/eggtoy_workspace/stm32_programmer/./Actor/Log.cpp:43: undefined reference to`vsnprintf'
build/obj/Log.cpp.o: In function `LogManager::printf(char const_, ...)':
/home/pan/eggtoy_workspace/stm32_programmer/./Actor/Log.cpp:43: undefined reference to `vsnprintf'
build/obj/core.ar(WString.cpp.o): In function`String::operator=(char const_)':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/WString.cpp:519: undefined reference to `utoa'
build/obj/core.ar(WString.cpp.o): In function`String::String(unsigned int, unsigned char)':
/home/pan/eggtoy_workspace/arduino-1.6.11/hardware/esp8266com/esp8266/cores/esp8266/WString.cpp:519: undefined reference to `utoa'
collect2: error: ld returned 1 exit status
make: *_\* [build/main.bin] Error 1

**Description**
I build with make. And am i missing any file?  Any help is appreciated.

**Comment by vortex314** [comment]
printf is defined in the Arduino ESP8266 libc_replacements.c 
Check the Makefile , it's referring to an installation of Arduino ESP8266 in your workspace.
See : https://github.com/esp8266/Arduino If uou don't have this it will not succeed.
You'll have to adapt the references in the Makefile.

I'll be changing my project later to use a gitbub submodule referring to the ESP8266 Arduino. So it get's automatically included

**Comment by duxiaoshi** [comment]
**The Makefile**

> 20 #=== Project specific definitions: sketch and list of needed libraries
>  21 ESP_LIBS ?= /home/pan/eggtoy_workspace/esp8266/libraries
>  22 ESPTOOL = ../esp8266/tools/esptool/esptool.py #//TODO
>  23 RESET = ../esp8266/tools/reset
>  24 INCLUDE_DIRS ?= ../Common/inc . ./Actor ./esp8266 ./include ../ArduinoJson
>  25 CORE_DIR ?= $(ESP_LIBS)
>  26 # USER_DIRS ?= $(ESP_LIBS)
>  27 # LIBS ?= .
>  28 # SKETCH ?= $(ESP_LIBS)/ESP8266WebServer/examples/HelloServer/HelloServer.ino
>  29 SKETCH ?= main.cpp
>  30 LIBS ?= $(ESP_LIBS)/Wire \
>  31         ../Common/src \
>  32         ../Common/inc \
>  33         ./Actor \
>  34         ../pubsubclient/src \
>  35        $(ESP_LIBS)/ESP8266WebServer \
>  36        $(ESP_LIBS)/EEPROM \
>  37        $(ESP_LIBS)/ESP8266WiFi \
>  38        $(ESP_LIBS)/ESP8266mDNS \
>  39 #       $(ESP_LIBS)/ESP8266WebServer \
>  40         ./driver 
>  41 
>  42 
>  43 # Esp8266 Arduino git location
>  44 ESP_ROOT ?= $(HOME)/eggtoy_workspace/esp8266
>  45 # Output directory
>  46 BUILD_ROOT ?= ./build
>  47 LOG ?= build/USB0.LOG
>  48 DEFINE ?= ANCHOR
>  49 
>  50 # Board definitions
>  51 FLASH_SIZE ?= 4M
>  52 FLASH_MODE ?= dio
>  53 FLASH_SPEED ?= 40
>  54 FLASH_LAYOUT ?= eagle.flash.4m.ld
>  55 
>  56 # Upload parameters
>  57 UPLOAD_SPEED ?= 576000 # 576000
>  58 UPLOAD_PORT ?= /dev/ttyUSB0
>  59 UPLOAD_VERB ?= -v
>  60 UPLOAD_RESET ?= nodemcu
>  61 
>  62 # OTA parameters
>  63 ESP_ADDR ?= ESP_DA6ABC
>  64 ESP_PORT ?= 8266
>  65 ESP_PWD ?= 123

and i have Arduino ESP8266 in my workspace. Still have errors.

> Linking ./build/main.bin
>   Versions: cef5ed6-dirty, 2.3.0-69-g4897e00
> build/obj/main.cpp.o: In function `waitConfig()':
> /home/pan/eggtoy_workspace/stm32_programmer/main.cpp:50: undefined reference to`sprintf'
> build/obj/main.cpp.o: In function `set<String&>':
> /home/pan/eggtoy_workspace/stm32_programmer/main.cpp:50: undefined reference to`sprintf'
> build/obj/core.ar(core_esp8266_main.cpp.o): In function `optimistic_yield':
> /home/pan/eggtoy_workspace/esp8266/cores/esp8266/core_esp8266_main.cpp:56: undefined reference to`printf'
> build/obj/core.ar(core_esp8266_main.cpp.o): In function `do_global_ctors':
> /home/pan/eggtoy_workspace/esp8266/cores/esp8266/core_esp8266_main.cpp:56: undefined reference to`printf'
> build/obj/core.ar(umm_malloc.c.o): In function `umm_info':
> /home/pan/eggtoy_workspace/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:991: undefined reference to`printf'
> /home/pan/eggtoy_workspace/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1024: undefined reference to `printf'
> /home/pan/eggtoy_workspace/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1043: undefined reference to`printf'
> build/obj/core.ar(umm_malloc.c.o):/home/pan/eggtoy_workspace/esp8266/cores/esp8266/umm_malloc/umm_malloc.c:1072: more undefined references to `printf' follow
> build/obj/core.ar(Print.cpp.o): In function`Print::printf(char const*, ...)':

I checked the libc_replacements.c, and i found that printf and sprintf are commented by '#if 0 '

> #if 0
> 
> int ICACHE_RAM_ATTR printf(const char\* format, ...) {
>     va_list arglist;
>     va_start(arglist, format);
>     int ret = ets_vprintf(ets_putc, format, arglist);
>     va_end(arglist);
>     return ret;
> }

**Comment by vortex314** [comment]
Indeed, you're on the right track. I changed this to : #if 1
Success !
